mapping = {
    "Business & Professional": "Business & Professional",
    "Religion & Spirituality": "Religion & Spirituality",
    "Health & Wellness": "Sports & Fitness",
    "Party or Social Gathering": ["Party", "Clubkonzerte", "Festivals"],
    "Food & Drink": "Oktoberfeste",
    "Music": [
        "Rock & Pop",
        "HipHop & R’n‘B",
        "Jazz & Blues",
        "Electronic & Dance",
        "Weitere Konzerte",
        "Festivals",
        "Schlager & Volksmusik",
    ],
    "Charity & Causes": "Festivals",
    "Performing & Visual Arts": ["Theater", "Musical", "Kleinkunst"],
    "Community & Culture": ["Festspiele", "Weitere Events", "Aktivitäten"],
    "Seasonal & Holiday": "Oktoberfeste",
    "Tradeshow, Consumer Show, or Expo": "Ausstellungen",
    "Concert or Performance": ["Rock & Pop", "Klassische Konzerte", "Comedy"],
    "Sports & Fitness": [
        "Weitere Sport-Events",
        "Fußball",
        "Eishockey",
        "Basketball",
        "Boxen & Wrestling",
        "Handball",
    ],
    "Fashion & Beauty": "Fashion & Beauty",
    "Science & Technology": "Technologie",
    "Film, Media & Entertainment": ["Kino", "Literatur", "Podcast"],
    "Seminar or Talk": "Seminar or Talk",
    "Christian": "Religion & Spirituality",
    "School Activities": "School Activities",
    "Attraction": "Attraction",
    "Conference": "Conference",
    "Government & Politics": "Government & Politics",
    "Travel & Outdoor": "Travel & Outdoor",
    "Family & Education": ["Kinder", "Family & Education"],
    "Workshop": ["Class, Training, or Workshop"],
    "Auto, Boat & Air": "Motorsport",
    "Home & Lifestyle": "Home & Lifestyle",
    "Class, Training, or Workshop": ["Class, Training, or Workshop"],
    "Appearance or Signing": "Appearance or Signing",
    "Tantra": "Tantra",
    "Convention": "Convention",
    "Other": "Weitere Events",
    "Hobbies & Special Interest": ["Hobbies & Special Interest", "Weitere Events"],
    "Halloween": "Oktoberfeste",
    "Event": "Event",
    "Dance Party": "Dance Party",
    "Festival or Fair": "Festivals",
    "Show": "Show",
    "Schlager & Volksmusik": "Schlager & Volksmusik",
    "HipHop & R’n‘B": "HipHop & R’n‘B",
    "Rock & Pop": "Rock & Pop",
    "Comedy": "Comedy",
    "Hard & Heavy": "Hard & Heavy",
    "Musical": "Musical",
    "Klassische Konzerte": "Klassische Konzerte",
    "Zirkus": "Zirkus",
    "Kabarett": "Kabarett",
    "VIP & Specials": "VIP & Specials",
    "Podcast": "Podcast",
    "Weitere Konzerte": "Weitere Konzerte",
    "Electronic & Dance": "Electronic & Dance",
    "Literatur": "Literatur",
    "Fußball": "Fußball",
    "Weitere Events": "Weitere Events",
    "Aktivitäten": "Aktivitäten",
    "Kinder": "Kinder",
    "Theater": "Theater",
    "Weitere Sport-Events": "Weitere Sport-Events",
    "Eishockey": "Eishockey",
    "Basketball": "Basketball",
    "Jazz & Blues": "Jazz & Blues",
    "Festivals": "Festivals",
    "Kleinkunst": "Kleinkunst",
    "Tanz": "Tanz",
    "Country & Folk": "Country & Folk",
    "Oper & Operette": "Oper & Operette",
    "Boxen & Wrestling": "Boxen & Wrestling",
    "Party": ["Party", "Clubkonzerte"],
    "Motorsport": "Motorsport",
    "Clubkonzerte": "Clubkonzerte",
    "Handball": "Handball",
    "Festspiele": "Festspiele",
    "Ausstellungen": "Ausstellungen",
    "Kino": "Kino",
    "Oktoberfeste": "Oktoberfeste",
}